import { useEffect, useState } from "react";
import studentService from "../services/studentService";
import jsPDF from "jspdf";

const Reports = () => {
  const [students, setStudents] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchStudents = async () => {
    try {
      const data = await studentService.getAllStudents();
      setStudents(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStudents();
  }, []);

  const generateReportCard = (student: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(18);
    doc.text("IKONEX ACADEMY", 105, 20, { align: "center" });
    doc.setFontSize(14);
    doc.text("STUDENT REPORT CARD", 105, 30, { align: "center" });
    
    doc.setFontSize(12);
    doc.text(`Name: ${student.name}`, 20, 50);
    doc.text(`Student ID: ${student.studentId}`, 20, 60);
    doc.text(`Class: ${student.classStream?.name || "N/A"}`, 20, 70);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 80);

    // Scores Table
    doc.text("SUBJECT          MARKS     GRADE", 20, 100);
    let y = 110;

    if (student.scores && student.scores.length > 0) {
      student.scores.forEach((score: any) => {
        const grade = score.marks >= 80 ? "A" : score.marks >= 70 ? "B" : score.marks >= 60 ? "C" : "D";
        doc.text(`${score.subject?.name || "Subject"}     ${score.marks}      ${grade}`, 20, y);
        y += 10;
      });
    } else {
      doc.text("No scores recorded yet", 20, y);
    }

    // Footer
    doc.setFontSize(10);
    doc.text("Generated by Ikonex Academy Student Management System", 105, 280, { align: "center" });

    doc.save(`${student.name.replace(/\s+/g, "_")}_Report_Card.pdf`);
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Reports</h1>
        <p className="text-gray-600">Generate and download official report cards</p>
      </div>

      <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100">
        <h2 className="text-2xl font-semibold mb-6">Individual Student Report Cards</h2>
        
        {loading ? (
          <p>Loading students...</p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {students.map((student) => (
              <div key={student.id} className="border border-gray-200 rounded-xl p-6 hover:shadow-md transition">
                <h3 className="font-semibold text-lg">{student.name}</h3>
                <p className="text-gray-600 text-sm">{student.studentId}</p>
                <p className="text-gray-500 text-sm mt-1">{student.classStream?.name}</p>
                
                <button
                  onClick={() => generateReportCard(student)}
                  className="mt-6 w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition"
                >
                  Download Report Card
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Reports;
